apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: valerix
type: Opaque
stringData:
  POSTGRES_USER: valerix
  POSTGRES_PASSWORD: valerix_prod_secret_2026
  POSTGRES_DB: postgres
